### ISSUE TITLE
TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64, int32

### ISSUE THREAD

**Issue by WuZhuoran** [Apm5/tensorflow_2.0_tutorial#3]
When running the `ResNet_CIFAR.py`, it will raise an error, after first epoch training.

```
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 390/390 [00:42<00:00,  9.27it/s]
ce_loss:1.753367, l2_loss:0.201427, accuracy:0.355829
  0%|                                                                                                                   | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tf2_train_cifar.py", line 190, in <module>
    test(model, test_images, test_labels)
  File "tf2_train_cifar.py", line 154, in test
    loss, prediction = test_step(model, x, y)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    tf2_train_cifar.py:116 test_step  *
        prediction = model(x, training=False)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:778 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py:717 call
        convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py:891 _run_internal_graph
        output_tensors = layer(computed_tensors, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:778 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/convolutional.py:213 call
        outputs = self._convolution_op(inputs, self.kernel)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py:1176 __call__
        return self.conv_op(inp, filter)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py:662 __call__
        return self.call(inp, filter)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py:252 __call__
        name=self.name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py:2052 conv2d
        name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_nn_ops.py:969 conv2d
        data_format=data_format, dilations=dilations, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py:576 _apply_op_helper
        param_name=input_name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py:61 _SatisfiesTypeConstraint
        ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))

    TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64, int32
```

Then I found that the error occurred in `test` function
https://github.com/Apm5/tensorflow_2.0_tutorial/blob/04bcfc3e04eb3846549cd5bedd423d8af7468239/CNN/ResNet_CIFAR.py#L181

Where after reading the images, unlike `train` function, after `images_augment`, the dtype will be `tf.float32`.
But for `test` function, it is still `uint8` type. 

The solution is to add a line:

`x = tf.cast(x, tf.float32)`

**Comment by Apm5** [comment]
@WuZhuoran 
Thank you for attention!
I have fix this error

by the way, would you please report your package version, such as tf and numpy. The error do not raise when I run the code

**Comment by WuZhuoran** [comment]
@Apm5 

I am using `nvcr.io/nvidia/tensorflow:20.03-tf2-py3` as docker image, and here is my package info:

tensorflow `2.1.0`   
numpy `1.17.2`
